/**
 * Apply pending Drizzle-generated SQL migrations to the database.
 *
 * Usage: `pnpm --filter @workspace/db run migrate`
 *
 * Reads `./migrations/*.sql` (generated by `pnpm run generate` from
 * Drizzle schema diffs), creates/updates the `__drizzle_migrations`
 * tracking table, applies anything new, then runs the trigger / seed
 * SQL in `./sql/` afterwards (those are idempotent and the source of
 * truth for non-schema database state).
 *
 * Designed to be called from the production deploy path. Safe to run
 * repeatedly: drizzle's migrator skips already-applied migrations.
 */
import path from "node:path";
import { readFile } from "node:fs/promises";
import pg from "pg";
import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";

const { Pool } = pg;

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL must be set");
}

const POST_MIGRATE_SQL = ["audit_log_append_only.sql", "platform_settings_seed.sql"];

async function main() {
  const pool = new Pool({ connectionString: process.env.DATABASE_URL });
  const db = drizzle(pool);

  const migrationsFolder = path.join(import.meta.dirname, "..", "migrations");
  console.log(`[migrate] Applying versioned migrations from ${migrationsFolder}…`);

  try {
    await migrate(db, { migrationsFolder });
    console.log("[migrate] Versioned migrations applied.");

    for (const file of POST_MIGRATE_SQL) {
      const fullPath = path.join(import.meta.dirname, "..", "sql", file);
      console.log(`[migrate] Applying idempotent ${file}…`);
      const sql = await readFile(fullPath, "utf8");
      await pool.query(sql);
    }

    console.log("[migrate] Done.");
  } finally {
    await pool.end();
  }
}

main().catch((err) => {
  console.error("[migrate] failed:", err);
  process.exit(1);
});
